apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: quote-php
  template: quote-php-mysql-persistent-template
metadata:
  annotations:
    openshift.io/display-name: Quote PHP Application and MySQL 5.7
  creationTimestamp: "2021-01-17T14:31:40Z"
  managedFields:
  - apiVersion: template.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:labels:
        .: {}
        f:app: {}
        f:template: {}
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/display-name: {}
      f:objects: {}
      f:parameters: {}
    manager: oc
    operation: Update
    time: "2021-01-17T14:31:40Z"
  name: quote-php-persistent
  namespace: dyuen-deploy
  resourceVersion: "101796097"
  selfLink: /apis/template.openshift.io/v1/namespaces/dyuen-deploy/templates/quote-php-persistent
  uid: 3b1ab4a7-cc80-42af-aa64-6fd1016578b1
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: mysql
    name: mysql
  spec:
    containers:
    - env:
      - name: MYSQL_ROOT_PASSWORD
        value: r00tpa55
      - name: MYSQL_USER
        value: user1
      - name: MYSQL_PASSWORD
        value: mypa55
      - name: MYSQL_DATABASE
        value: quotes
      image: quay.io/${RHT_OCP4_QUAY_USER}/do180-mysql-57-rhel7
      name: mysql
      ports:
      - containerPort: 3306
        name: mysql
      volumeMounts:
      - mountPath: /var/lib/mysql/data
        name: db-volume
      - mountPath: /var/lib/mysql/init
        name: db-init
    volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: dbclaim
    - name: db-init
      persistentVolumeClaim:
        claimName: dbinit
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: quote-php
    name: quote-php
  spec:
    containers:
    - env:
      - name: MYSQL_ENV_MYSQL_DATABASE
        value: items
      - name: MYSQL_ENV_MYSQL_USER
        value: user1
      - name: MYSQL_ENV_MYSQL_PASSWORD
        value: mypa55
      image: quay.io/${RHT_OCP4_QUAY_USER}/do180-quote-php
      name: quote-php
      ports:
      - containerPort: 8080
        name: php-http
      resources:
        limits:
          cpu: "0.5"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: quote-php
    name: quote-php
  spec:
    ports:
    - port: 8080
    selector:
      name: quote-php
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: mysql
    name: mysql
  spec:
    ports:
    - port: 3306
    selector:
      name: mysql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: dbinit
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: dbclaim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
parameters:
- description: Quay namespace the images are stored in
  name: RHT_OCP4_QUAY_USER
  required: true
